### ISSUE TITLE
Interval During Question

### ISSUE THREAD

**Issue by jduke99** [DBCG/cql_engine#146]
I have created an interval and am seeing an odd finding. Hoping someone can help clarify.

My interval is this:
Interval[2177-10-18T16:30:00, 2177-10-19T16:30:00]

My target event occurs at this time:
DateTimeType[2177-10-19T00:00:00+00:00]

When I run a query in this clunky way, it returns results correctly:
```
define "Diagnoses":
[Condition: Code in "My Diagnoses"] Dx
    with "Risk Window" P
    such that Dx.onset after start of P
    and Dx.onset before end of P
```

But when I run a query using the `during` syntax it returns empty :
```
define "Diagnoses":
[Condition: Code in "My Diagnoses"] Dx
    with "Risk Window"  P
    such that Dx.onset during P
```

It would seem that the two queries are equivalent, but am I missing something?

Thanks!

**Comment by c-schuler** [comment]
Those two queries are almost equivalent. The "during" (or "included in") operator has a precision element. When that precision element is not specified, the precision defaults to millisecond precision. Since your interval DateTime boundaries are specified to second, the comparison is uncertain, which will typically evaluate to null. 

Try the following query:
```
define "Diagnoses":
[Condition: Code in "My Diagnoses"] Dx
    with "Risk Window"  P
    such that Dx.onset during day of P
```

Here are some links to further reading on this subject:
[IncludedIn operator](http://cql.hl7.org/09-b-cqlreference.html#included-in)
[CQL Precision based timing and Uncertainty](http://cql.hl7.org/05-languagesemantics.html#precision-based-timing)

Hope that helps!

**Comment by jduke99** [comment]
Thank you so much @c-schuler!  Makes perfect sense.
