### ISSUE TITLE
Using in day of with Interval parameters

### ISSUE THREAD

**Issue by jscherer-motivemi** [DBCG/cql_engine#184]
We are trying to use the following CQL expression:

```
parameter MeasurementPeriod default Interval[DateTime(((year from Today()) - 1),  1,  1,  0,  0,  0), DateTime(((year from Today()) - 1), 12, 31, 23, 59, 59)]

define InitialDMEyeExamProcedure: [Procedure] DMEP where DMEP.performed.start in day of MeasurementPeriod
```

A couple of questions:
1. Is this a valid statement?
2. If this is a valid statement, it does not execute correctly for us. The retrieve does not identify a Procedure resource where the performed.start is in the MeasurementPeriod.

Thanks for the assistance,
Julie

**Comment by c-schuler** [comment]
Hi Julie,

1. That is actually not valid as start is a reserved keyword in CQL, so that should be quoted (i.e. DMEP.performed."start"). However, I think that is just an oversight as the corresponding issue in your Jira (RAS-2962) correctly wraps the start keyword in quotes.

2. This should work... Would you mind providing the patient data that you're using for testing?

**Comment by jscherer-motivemi** [comment]
@c-schuler , we confirmed that this works in v1.2.58.
