### ISSUE TITLE
JpaDataProvider should be able to handle the case where it is passed a string rather than a code

### ISSUE THREAD

**Issue by okeefm** [DBCG/cql_engine#185]
In the VTE-1 measure on cqf-ruler, the `EncounterDiagnosis` function in `MatGlobalCommonFunctions` returns an array of `String`s that are IDs of `Condition` elements from the `diagnosis` field on a given `Encounter`. When these are passed to the `JpaDataProvider` for retrieval, it treats them as an array of `Code` objects instead, and the server throws a `java.lang.ClassCastException` because it is unable to automatically convert a `String` to a `Code`. Bryn said that this case would need to be accommodated in cqf-ruler/cql_engine, and asked me to post a ticket here.

Full stacktrace is attached to the issue below.
[cqfr_error_2.txt](https://github.com/DBCG/cql_engine/files/3186651/cqfr_error_2.txt)

**Comment by brynrhodes** [comment]
The following example reproduces the issue:

    library Test
    using FHIR version '3.0.0'
    include FHIRHelpers version '3.0.0' called FHIRHelpers
    context Patient
    define IdSearch: [Condition: id in '365']

Since the retrieve is expecting a Code, the engine should be able to convert the string to a code automatically. However, passing a Code will work as well:

    define IdSearch: [Condition: _id in Code { code: '365'}]

Note also that the name of the code path is `_id`, not `id`, since the code path is actually specifying a search parameter, and the "id" search parameter for all resources in FHIR is named `_id`.

**Comment by brynrhodes** [comment]
For simplicity, the engine should also try to match code paths to search params, so it should know to change `id` to `_id` for all resources.
