### ISSUE TITLE
BaseFhirDataProvider missing IBaseDatatypeElement in resolveRuntimeDefinition

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#24]
resolveRuntimeDefinition method of BaseFhirDataProvider should handle IBaseDatatypeElement in addition to IBaseBackboneElement and IBaseElement. This is the interface for several internal "Component" classes in HAPI FHIR model, including org.hl7.fhir.instance.model.Timing$TimingRepeatComponent which is used for MedicationOrder.dosageInstruction.timing.

**Comment by c-schuler** [comment]
I think this was erring due to a missing null check in the QueryEvaluator. I added that in the latest [commit](https://github.com/DBCG/cql_engine/commit/c4b1aa8a7c6e98281b46bc4e6c6143ebcd23770e). Pushed the fix to the 1.2.22-SNAPSHOT of the engine.

I added the following [test](https://github.com/DBCG/cql_engine/blob/master/cql-engine-fhir/src/test/java/org/opencds/cqf/cql/data/fhir/TestFhirDataProviderHL7.java#L62-L66) based on the following [code](https://github.com/DBCG/cql_engine/blob/master/cql-engine-fhir/src/test/resources/org/opencds/cqf/cql/data/fhir/TestFhirDataProviderHL7.cql#L18-L20) to verify. 

If you have issues with the new code, please let me know =)
