### ISSUE TITLE
Difference in days produce wrong result

### ISSUE THREAD

**Issue by mdnazmulkarim** [DBCG/cql_engine#301]
difference in days between @2017-03-12T00:00:00-07:00 and @2017-03-13T00:00:00-06:00
difference in days between DateTime(2017, 3, 12, 0, 0, 0, 0, -7.0) and DateTime(2017, 3, 13, 0, 0, 0, 0, -6.0)
should result 1 but instead it's resulting 0

**Comment by c-schuler** [comment]
DateTime operations with timezone offsets can be tricky. For example, the test provided will return 0 when executed in MST or PST, but will return 1 when executed in CST or EST. The reason for this is due to offset normalization. When `difference in days between @2017-03-12T00:00:00-07:00 and @2017-03-13T00:00:00-06:00` is executed in MST, then `@2017-03-13T00:00:00-06:00` gets normalized to `@2017-03-12T23:00:00-07:00` and the operation returns 0 because no boundaries where crossed.

**Comment by brynrhodes** [comment]
On this one, I think the issue is that since the calculation is happening at days, the normalization should not occur:
https://cql.hl7.org/15-h-timeintervalcalculations.html#difference-calculations

**Comment by c-schuler** [comment]
Ok, so then this would also be the justification for the result in #300, right? The time elements are truncated because the `weeks` precision is coarser than the time elements.

**Comment by JPercival** [comment]
Resolved by #332
