### ISSUE TITLE
Can xpp3_xpath be removed?

### ISSUE THREAD

**Issue by jillrdoty** [DBCG/cql_engine#451]
When integrating the engine into our solution, the xpp3_xpath jar was flagged with a non-Apache license.  I attempted to remove this dependency and the project builds fine, all tests pass.  Am curious what the purpose of the dependency is, does it serve some purpose at runtime?

To be clear: not asking about the xpp3 artifact, I do see tests fail when that dependency isn't present.

**Comment by JPercival** [comment]
Hi @jillrdoty.

The xpp3_xpath jar actually is a requirement for the ucum service and several hapi dependencies for the engine.fhir module. The test coverage isn't as good for that module as it is for the engine itself, so that's probably why you're not seeing failing tests. The reason it's called out explicitly in the pom is so that we can control the version that's used. Otherwise, we'd transitively pick up a version from either the ucum service or hapi. If you're not using either the ucum service or the engine.fhir modules you can probably remove the dependency.

**Comment by jillrdoty** [comment]
Thanks for the quick response and explanation.  Oddly enough when I removed the dependency from the poms and looked at the dependency tree maven generated I didn't see it being pulled in transitively, but looking at the ucum pom I'm unclear why it wouldn't be.  Thanks again!
