### ISSUE TITLE
Could not resolve external function provider when it  is invoked in an included library

### ISSUE THREAD

**Issue by dmartino88** [DBCG/cql_engine#478]
Tool provides an Exception in CQL Execution when an external function is invoked in an included library.
For example, if there two libraries called Library1 and Library2 where Library1 define and invoke an external function when Library2 try to invoke the external function defined in Library1 the tool gives the following exception 

_ERROR: Exception in CQL Execution.
Could not resolve external function provider for library 'org.cqframework.cql.elm.execution.VersionedIdentifier@2b43e80a[id=Library1, system=<null>, version=0.0.1
]'.
org.opencds.cqf.cql.exception.CqlException: Could not resolve external function provider for library 'org.cqframework.cql.elm.execution.VersionedIdentifier@2b43e80a[id=Library1, system=<null>, version=0.0.1
]'._

Following the pseudo-code that I wrote:
```
//***************Library1************************
library MyLibrary1 version '0.0.1'
define function myExternalFunction(key String) returns String : external

define "myResultExternalFunction":  
                  myExternalFunction(key String)

define function getResultFromLibrary1(): //for seplicity I did not add the return 
                 "myResultExternalFunction"

//***********Library2*******************************
library MyLibrary2 version '0.0.1'

include MyLibrary1 version '0.0.1' called MyLibrary1

define "myResult": MyLibrary1.getResultFromLibrary1() //this instruction gives error since it uses data coming from external function declared in MyLibrary1
```

**I have no problem when in Mylibrary2 I invoke functions of MyLibrary1 that don't use/invoke external functions.** @JPercival

**Comment by JPercival** [comment]
Hi dmartino88!

How are you executing that CQL?  The `external` keyword in CQL means that some other component provides the implementation for that function (such as a proprietary Java library, native machine code, etc). Since it's marked `external` the CqlEngine doesn't know how to invoke the function. You tell it how to do that by registering an `ExternalFunctionProvider` with the `Context`. Note that Atom, cqf-ruler, and the cql-runner currently don't have built-in support for registering that kind of provider, so it currently means rolling your own custom execution environment to use that CQL feature.

**Comment by JPercival** [comment]
Closing this due to answering the question. Feel free to re-open if needed.
