### ISSUE TITLE
Add cache for FhirModelResolver type-to-class resolution

### ISSUE THREAD

**Issue by msargentibm** [DBCG/cql_engine#489]
I recently hit an issue when evaluating CQL where the engine spent multiple hours resolving FHIR types with `R4FhirModelResolver.resolveType()`. I was able to patch my code locally to cache the results of `resolveType()`, and then the same CQL evaluated in about 20 seconds. This issue is to request the addition caching for the method `public Class<?> resolveType(String typeName)` in either the `R4FhirModelResolver` or the base `FhirModelResolver` class.

I noticed the FhirModelResolver class has a TODO to add caching for some of its operations:
https://github.com/DBCG/cql_engine/blob/master/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/FhirModelResolver.java#L44.

I'd be happy to try PR a change, but I was wondering if someone would be able to offer some guidance into the sort of caching the team had in mind for this situation. Is there a caching strategy that is typically used in this project (something like Spring/JCache), or would a simple Map suffice in this case?

**Comment by JPercival** [comment]
We elected to keep caching separate due to some edge cases. It's implemented as a decorator here if you want it:

https://github.com/DBCG/cql-evaluator/blob/master/evaluator.engine/src/main/java/org/opencds/cqf/cql/evaluator/engine/model/CachingModelResolverDecorator.java

**Comment by msargentibm** [comment]
Thanks! Would you mind if I opened a PR to change the TODO on `FhirModelResolver` to something that calls out the fact that caching is implemented elsewhere?

**Comment by msargentibm** [comment]
While I'm thinking of caching, is there caching implemented for the note here too: https://github.com/DBCG/cql_engine/blob/5be0595637e75d9c89c02a27e505b87e4e7e789a/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/searchparam/SearchParameterResolver.java#L104?

I tried a quick search, but did not come across a similar decorator. It also seems slightly trickier to implement currently since the `normalizePath` method is private in that class.

**Comment by JPercival** [comment]
We're testing out some different options for that aspect. For example, figuring that out via capability statement. Here's a draft PoC PR for reference (not likely to ever be merged - just me testing out a couple things and making it visible for others):

https://github.com/DBCG/cql_engine/pull/440

**Comment by JPercival** [comment]
Resolved by #490

**Comment by msargentibm** [comment]
Thanks for the pointer to #440. I completely forgot about that PR even though I commented on it at one point 😄

**Comment by JPercival** [comment]
I suppose that I should mention that we're considering all sorts of options for future enhancements to make this all better. Code-gen for the model resolver so that dynamic resolution isn't needed, depending directly on the ELM model-info, adding search-paths directly to ELM, etc. There are just a bunch of considerations such as how portable we want the ELM to be (from a "total CQL ecosystem" perspective), how hard runtime optimizations (IOW, query planning) for a given target environment are, etc. Anyway, I wouldn't take anything that happens in model resolution as the expected future state at this point. We just haven't fully nailed down the approach or priority just yet.
